force-app/main/default/objects/xDO_TTHAIR_Flight__c/xDO_TTHAIR_Flight__c.object-meta.xml
<CustomObject>
    <label>TTH Flight Schedule</label>
    <nameField>
        <displayFormat>FL-{000000}</displayFormat>
        <label>Flight Entry#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flight Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/xDO_TTHAIR_Flight__c/fields/xDO_TTHAIR_ARR_CODE__c.field-meta.xml
<CustomField>
    <fullName>xDO_TTHAIR_ARR_CODE__c</fullName>
    <formula>xDO_TTHAIR_Flight__r.xDO_TTHAIR_ARR_CODE__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ARR CODE</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xDO_TTHAIR_Flight__c/fields/xDO_TTHAIR_Arrival_City__c.field-meta.xml
<CustomField>
    <fullName>xDO_TTHAIR_Arrival_City__c</fullName>
    <label>Arrival City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xDO_TTHAIR_Flight__c/fields/xDO_TTHAIR_Arrival_Time__c.field-meta.xml
<CustomField>
    <fullName>xDO_TTHAIR_Arrival_Time__c</fullName>
    <label>Arrival Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/xDO_TTHAIR_Flight__c/fields/xDO_TTHAIR_DEP_CODE__c.field-meta.xml
<CustomField>
    <fullName>xDO_TTHAIR_DEP_CODE__c</fullName>
    <formula>xDO_TTHAIR_Flight__r.xDO_TTHAIR_DEP_CODE__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DEP CODE</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xDO_TTHAIR_Flight__c/fields/xDO_TTHAIR_Departure_City__c.field-meta.xml
<CustomField>
    <fullName>xDO_TTHAIR_Departure_City__c</fullName>
    <label>Departure City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xDO_TTHAIR_Flight__c/fields/xDO_TTHAIR_Departure_Time__c.field-meta.xml
<CustomField>
    <fullName>xDO_TTHAIR_Departure_Time__c</fullName>
    <label>Departure Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/xDO_TTHAIR_Flight__c/fields/xDO_TTHAIR_Flight__c.field-meta.xml
<CustomField>
    <fullName>xDO_TTHAIR_Flight__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Flight Number</label>
    <referenceTo>xDO_TTHAIR_FlightNumber__c</referenceTo>
    <relationshipName>Flight_Schedules</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/xDO_TTHAIR_Flight__c/fields/xDO_TTHAIR_Flight_Name__c.field-meta.xml
<CustomField>
    <fullName>xDO_TTHAIR_Flight_Name__c</fullName>
    <formula>xDO_TTHAIR_Flight__r.xDO_TTHAIR_Flight_Name__c +&apos; - &apos;+  xDO_TTHAIR_Flight__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Flight Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xDO_TTHAIR_Flight__c/fields/xDO_TTHAIR_FlightNumber__c.field-meta.xml
<CustomField>
    <fullName>xDO_TTHAIR_FlightNumber__c</fullName>
    <formula>xDO_TTHAIR_Flight__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Flight#</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xDO_TTHAIR_FlightNumber__c/xDO_TTHAIR_FlightNumber__c.object-meta.xml
<CustomObject>
    <label>TTH Flight Number</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flight Number</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/xDO_TTHAIR_FlightNumber__c/fields/xDO_TTHAIR_ARR_CODE__c.field-meta.xml
<CustomField>
    <fullName>xDO_TTHAIR_ARR_CODE__c</fullName>
    <label>ARR CODE</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xDO_TTHAIR_FlightNumber__c/fields/xDO_TTHAIR_DEP_CODE__c.field-meta.xml
<CustomField>
    <fullName>xDO_TTHAIR_DEP_CODE__c</fullName>
    <label>DEP CODE</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xDO_TTHAIR_FlightNumber__c/fields/xDO_TTHAIR_Flight_Name__c.field-meta.xml
<CustomField>
    <fullName>xDO_TTHAIR_Flight_Name__c</fullName>
    <label>Flight Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xDO_TTHAIR_Ininerary__c/xDO_TTHAIR_Ininerary__c.object-meta.xml
<CustomObject>
    <label>TTH Itinerary</label>
    <nameField>
        <displayFormat>IT-{000000}</displayFormat>
        <label>Itinerary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itineraries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/xDO_TTHAIR_Ininerary__c/fields/xDO_TTHAIR_ARR_CODE__c.field-meta.xml
<CustomField>
    <fullName>xDO_TTHAIR_ARR_CODE__c</fullName>
    <formula>xDO_TTHAIR_Flight_Schedule__r.xDO_TTHAIR_ARR_CODE__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ARR_CODE</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xDO_TTHAIR_Ininerary__c/fields/xDO_TTHAIR_Arrival_City__c.field-meta.xml
<CustomField>
    <fullName>xDO_TTHAIR_Arrival_City__c</fullName>
    <formula>xDO_TTHAIR_Flight_Schedule__r.xDO_TTHAIR_Arrival_City__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Arrival City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xDO_TTHAIR_Ininerary__c/fields/xDO_TTHAIR_Contact__c.field-meta.xml
<CustomField>
    <fullName>xDO_TTHAIR_Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Itineraries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/xDO_TTHAIR_Ininerary__c/fields/xDO_TTHAIR_DEP_CODE__c.field-meta.xml
<CustomField>
    <fullName>xDO_TTHAIR_DEP_CODE__c</fullName>
    <formula>xDO_TTHAIR_Flight_Schedule__r.xDO_TTHAIR_DEP_CODE__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DEP CODE</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xDO_TTHAIR_Ininerary__c/fields/xDO_TTHAIR_Departure_City__c.field-meta.xml
<CustomField>
    <fullName>xDO_TTHAIR_Departure_City__c</fullName>
    <formula>xDO_TTHAIR_Flight_Schedule__r.xDO_TTHAIR_Departure_City__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Departure City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xDO_TTHAIR_Ininerary__c/fields/xDO_TTHAIR_Flight__c.field-meta.xml
<CustomField>
    <fullName>xDO_TTHAIR_Flight__c</fullName>
    <formula>xDO_TTHAIR_Flight_Schedule__r.xDO_TTHAIR_Flight__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Flight#</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xDO_TTHAIR_Ininerary__c/fields/xDO_TTHAIR_Flight_Schedule__c.field-meta.xml
<CustomField>
    <fullName>xDO_TTHAIR_Flight_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Flight Schedule</label>
    <referenceTo>xDO_TTHAIR_Flight__c</referenceTo>
    <relationshipName>Itineraries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/xDO_TTHAIR_Ininerary__c/fields/xDO_TTHAIR_PNR__c.field-meta.xml
<CustomField>
    <fullName>xDO_TTHAIR_PNR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PNR</label>
    <referenceTo>xDO_TTHAIR_PNR__c</referenceTo>
    <relationshipName>Itineraries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/xDO_TTHAIR_PNR__c/xDO_TTHAIR_PNR__c.object-meta.xml
<CustomObject>
    <label>TTH PNR</label>
    <nameField>
        <label>PNR Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PNRs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/xDO_TTHAIR_PNR__c/fields/xDO_TTHAIR_Contact__c.field-meta.xml
<CustomField>
    <fullName>xDO_TTHAIR_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>PNRs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/xDO_TTHAIR_PNR__c/fields/xDO_TTHAIR_Flight__c.field-meta.xml
<CustomField>
    <fullName>xDO_TTHAIR_Flight__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Flight Schedule DONOT USE</label>
    <referenceTo>xDO_TTHAIR_Flight__c</referenceTo>
    <relationshipName>PNRs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/xDO_TTHAIR_PNR__c/fields/xDO_TTHAIR_PNR_Status__c.field-meta.xml
<CustomField>
    <fullName>xDO_TTHAIR_PNR_Status__c</fullName>
    <label>PNR Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Confirmed</fullName>
                <default>true</default>
                <label>Confirmed</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/tth_FightDetailsController.cls
public with sharing class tth_FightDetailsController {
    public tth_FightDetailsController() {

    }

    @AuraEnabled(cacheable=true)
    public static List<xDO_TTHAIR_Flight__c> getFlightInformation(string recordIdContact) {

        List<xDO_TTHAIR_Flight__c> objFlightDetails = new List<xDO_TTHAIR_Flight__c>();
        try{
        xDO_TTHAIR_PNR__c objPNR = [select Id, Name from xDO_TTHAIR_PNR__c where xDO_TTHAIR_Contact__c = :recordIdContact and xDO_TTHAIR_PNR_Status__c = 'Confirmed' LIMIT 1 ];
        xDO_TTHAIR_Ininerary__c objItineray = [select Id, xDO_TTHAIR_Flight_Schedule__c from xDO_TTHAIR_Ininerary__c where xDO_TTHAIR_PNR__c =: objPNR.Id];
        objFlightDetails = [select xDO_TTHAIR_FlightNumber__c,xDO_TTHAIR_Flight_Name__c,xDO_TTHAIR_DEP_CODE__c,xDO_TTHAIR_ARR_CODE__c, xDO_TTHAIR_Arrival_Time__c,xDO_TTHAIR_Departure_Time__c,xDO_TTHAIR_Departure_City__c,xDO_TTHAIR_Arrival_City__c from xDO_TTHAIR_Flight__c where Id =:objItineray.xDO_TTHAIR_Flight_Schedule__c Limit 1];
        }
        catch(Exception ex){
          System.debug(ex);
        }
        return objFlightDetails;
        
    }
}