force-app/main/default/objects/xDO_TTHAIR_Einstein_Replies__c/xDO_TTHAIR_Einstein_Replies__c.object-meta.xml
<CustomObject>
    <label>TTH Einstein Replies</label>
    <nameField>
        <label>TTH Einstein Replies Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TTH Einstein Replies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/xDO_TTHAIR_Einstein_Replies__c/fields/xDO_TTHAIR_Identifier__c.field-meta.xml
<CustomField>
    <fullName>xDO_TTHAIR_Identifier__c</fullName>
    <displayFormat>message{0}</displayFormat>
    <label>Identifier</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/xDO_TTHAIR_Einstein_Replies__c/fields/xDO_TTHAIR_Response_Message__c.field-meta.xml
<CustomField>
    <fullName>xDO_TTHAIR_Response_Message__c</fullName>
    <label>Response Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/xDO_TTHAIR_Einstein_Replies__c/fields/xDO_TTHAIR_Source__c.field-meta.xml
<CustomField>
    <fullName>xDO_TTHAIR_Source__c</fullName>
    <label>Message Source</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/tth_einsteinRepliesApexController.cls
public with sharing class tth_einsteinRepliesApexController {
    public tth_einsteinRepliesApexController() {

    }
    
    @AuraEnabled
    public static EinsteinResponseWrapper getChatRecord() {
        
        List<xDO_TTHAIR_Einstein_Replies__c> msgs = [SELECT Name, xDO_TTHAIR_Identifier__c , xDO_TTHAIR_Response_Message__c,xDO_TTHAIR_Source__c   FROM xDO_TTHAIR_Einstein_Replies__c ];
        LiveChatTranscript ct = [SELECT Id, Name FROM LiveChatTranscript WHERE STATUS = 'InProgress' ORDER BY CreatedDate DESC LIMIT 1];
        EinsteinResponseWrapper epw = new EinsteinResponseWrapper();
        epw.lstReplies = msgs;
        epw.chatTranscript = ct;        
        return epw;
    }
    
    
    public class EinsteinResponseWrapper {
        
        @AuraEnabled
        public List<xDO_TTHAIR_Einstein_Replies__c> lstReplies {get; set;}
        @AuraEnabled
        public LiveChatTranscript chatTranscript {get; set;}
        
    }
}